### ISSUE TITLE
Unexpected token on start

### ISSUE THREAD

**Issue by johanguse** [aderaaij/totallystatical#7]
I run yarn install or run npm install and after gulp
Always give me same error.

Node 7.7.2
Yarn 1.3.2

`gulpfile.js\tasks\buildProduction.js:18
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireDir (project_folder\node_modules\require-dir\index.js:123:33)`

**Comment by aderaaij** [comment]
Hi @johanguse, thanks for the error report! The error seems to say there's a syntax problem, but I can't seem to reproduce this. Is it a possibility to upgrade your Node version? I've just been checking [node.green](http://node.green/) and it seems there are a couple of things that would throw an error on 7.1.x that don't throw errors on 8.x. I'll try and do some more research but if you could try a different node version that would be great

**Comment by aderaaij** [comment]
I've installed NVM and Node v7.7.2 and it's definitely a node version issue. It's probably [something with trailing comma's](http://node.green/#ES2017-features-trailing-commas-in-function-syntax).

As I do everything with arrow functions / es6 style I kind of dropped support for older versions than 8.0. I'll add that to the readme. 

I'll close this issue, but if I can help you with anything, please let me know!

**Comment by johanguse** [comment]
Works on Node 8.*
Thank you!
